### ISSUE TITLE
uri: add mechanism to add / remove query parameters

### ISSUE THREAD

**Issue by dhasenan** [rikkimax/alphaPhobos#1]
I'm not seeing any way to modify a URIAddress's query parameters. I absolutely need to add query parameters, and I strongly wish to overwrite them.

(Specific use case: CouchDB client. I have a range over a query. I will have to repeatedly call the server with the same base URL but changing the 'startKey' parameter each time.)

**Comment by rikkimax** [comment]
I have decided against this.
URIAddress primary goal is to retrieve information in a standardised format, in other words safely.

A method to create URI's would be a good feature. However like creating a full URI, modifying query parameters falls under 'a LOT of work for no real world gain'.

I was thinking perhaps a constructor to do this. It seems fitting.
