### ISSUE TITLE
uri: documentation

### ISSUE THREAD

**Issue by dhasenan** [rikkimax/alphaPhobos#4]
There's almost no documentation on any member in the uri module.

**Comment by rikkimax** [comment]
Every member is either /// or has a full on ddoc comment.
Unfortunately my website is down right now. If it wasn't I would link an (old) generated documentation for it, which shows this to be the case.

And in almost all cases there will be a unittest shown as an example.

**Comment by dhasenan** [comment]
An empty documentation comment is not documentation. It's just telling ddoc not to hide the existence of that member.

**Comment by rikkimax** [comment]
Almost every function and method includes a unit test which is part of the DDOC as an example.
If you have something in mind, please PR it.
