### ISSUE TITLE
uri: URLs are not validated

### ISSUE THREAD

**Issue by dhasenan** [rikkimax/alphaPhobos#7]
`URIAddress("smb://@/%:")`

I rather feel that that should throw an exception.

Even if it really shouldn't, accessing the username and password certainly should.

**Comment by rikkimax** [comment]
This is how I interpret it:
smb://[user]@[hostname]/%:

This is valid.
In the case of user and hostname, it will just return null.

**Comment by dhasenan** [comment]
[RFC 1738](https://www.ietf.org/rfc/rfc1738.txt) says that the '<user>:<password>@' portion is optional _as a whole_, not piece by piece. An empty username and password can be explicitly passed, then, as in "smb://:@hostname/path".

"%:" is an invalid percent-encoded value.

**Comment by rikkimax** [comment]
I don't do encoding.
So not my problem :)
